### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by tea-se** [softozhik/prpid#12]
Find uncaught exception
```
./prpid.py /dev/null
Traceback (most recent call last):
  File "./prpid.py", line 18, in <module>
    launch = subprocess.Popen(arg[1:])
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/dev/null'
```

**Comment by softozhik** [comment]
closed this in commit 05ff2606a3ced53f4e7a82d2a9e4e553aa3d8b24
